### ISSUE TITLE
Support for escape strings like "mysql_real_escape_string"

### ISSUE THREAD

**Issue by 0x6369616e** [anarthal/mysql#55]
Is there a way how to escape a single string?

Can I use prepared statement for async queries?

**Comment by anarthal** [comment]
Hi,

There is currently no equivalent to `mysql_real_escape_string` (which performs client-side escaping).

You can achieve similar results with server-side escaping, via prepared statements. You can read more about prepared statement support [here](https://anarthal.github.io/mysql/mysql/prepared_statements.html). Prepared statements can be used with asynchronous code, by using `connection::async_prepare_statement` instead of `connection::prepare_statement` and `prepared_statement::async_execute` instead of `prepared_statement::execute`.

Please let me know if this solves your use case.

Cheers,
Rubén.
